"""Add fields for new categories

Revision ID: 343ec791cbec
Revises: 6d6d2e56957b
Create Date: 2025-09-28 12:24:18.121844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343ec791cbec'
down_revision = '6d6d2e56957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('doc_length', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('doc_format', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('doc_audience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pres_slides', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pres_audience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pres_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pres_duration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('info_data_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('info_viz_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('info_theme', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('info_elements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('anim_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('anim_duration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('anim_characters', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('anim_technique', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('web_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('web_technologies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('web_features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('web_responsive', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_analysis_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_viz_tools', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_output_format', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('trans_source_lang', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('trans_target_lang', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('trans_domain', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('trans_tone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sum_source_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sum_length', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sum_key_points', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sum_format', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('market_campaign_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('market_target_audience', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('market_platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('market_objective', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('edu_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('edu_subject', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('edu_format', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('edu_duration', sa.String(length=20), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('edu_duration')
        batch_op.drop_column('edu_format')
        batch_op.drop_column('edu_subject')
        batch_op.drop_column('edu_level')
        batch_op.drop_column('market_objective')
        batch_op.drop_column('market_platform')
        batch_op.drop_column('market_target_audience')
        batch_op.drop_column('market_campaign_type')
        batch_op.drop_column('sum_format')
        batch_op.drop_column('sum_key_points')
        batch_op.drop_column('sum_length')
        batch_op.drop_column('sum_source_type')
        batch_op.drop_column('trans_tone')
        batch_op.drop_column('trans_domain')
        batch_op.drop_column('trans_target_lang')
        batch_op.drop_column('trans_source_lang')
        batch_op.drop_column('data_output_format')
        batch_op.drop_column('data_viz_tools')
        batch_op.drop_column('data_analysis_type')
        batch_op.drop_column('data_source')
        batch_op.drop_column('web_responsive')
        batch_op.drop_column('web_features')
        batch_op.drop_column('web_technologies')
        batch_op.drop_column('web_type')
        batch_op.drop_column('anim_technique')
        batch_op.drop_column('anim_characters')
        batch_op.drop_column('anim_duration')
        batch_op.drop_column('anim_style')
        batch_op.drop_column('info_elements')
        batch_op.drop_column('info_theme')
        batch_op.drop_column('info_viz_type')
        batch_op.drop_column('info_data_type')
        batch_op.drop_column('pres_duration')
        batch_op.drop_column('pres_style')
        batch_op.drop_column('pres_audience')
        batch_op.drop_column('pres_slides')
        batch_op.drop_column('doc_audience')
        batch_op.drop_column('doc_format')
        batch_op.drop_column('doc_length')
        batch_op.drop_column('doc_type')

    # ### end Alembic commands ###
