"""Add audio, code, and video fields

Revision ID: 6d6d2e56957b
Revises: 
Create Date: 2025-09-28 03:16:30.567634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6d2e56957b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_duration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('audio_genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('audio_mood', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('audio_instruments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('code_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code_framework', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code_complexity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('code_purpose', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('video_duration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('video_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('video_resolution', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('video_frame_rate', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('video_aspect_ratio', sa.String(length=10), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('video_aspect_ratio')
        batch_op.drop_column('video_frame_rate')
        batch_op.drop_column('video_resolution')
        batch_op.drop_column('video_style')
        batch_op.drop_column('video_duration')
        batch_op.drop_column('code_purpose')
        batch_op.drop_column('code_complexity')
        batch_op.drop_column('code_framework')
        batch_op.drop_column('code_language')
        batch_op.drop_column('audio_instruments')
        batch_op.drop_column('audio_mood')
        batch_op.drop_column('audio_genre')
        batch_op.drop_column('audio_duration')

    # ### end Alembic commands ###
